indent = 4
margin = 92
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = false
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
trailing_comma = false
annotate_untyped_fields_with_any=false
format_docstrings = true
